<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "images".
 *
 * @property int $id
 * @property string $md
 * @property string $extensions
 * @property string $link
 */
class Images extends \yii\db\ActiveRecord
{

    const IMG_PATH = 'web/upload/';
    const IMG_DIR = '/upload/';

    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'images';
    }

    /**
     * @param bool $insert
     * @return bool
     */
    function beforeSave($insert)
    {
        $this->md = md5(substr(md5(microtime() . rand(0, 9999)), 0, 20).date("Y-m-d H:i:s"));
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['md', 'extensions', 'link'], 'string', 'max' => 255],
        ];
    }

    /**
     * @return bool|string
     */
    public function img_link() {
        if ($this->md && $this->extensions) {
            $file = self::IMG_DIR.$this->md.'.'.$this->extensions;
            return $file;
        } else {
            return FALSE;
        }

    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'md' => 'Имя файла',
            'extensions' => 'Расширение файла',
            'link' => 'Ссылка (откуда был загружен)',
        ];
    }
}
